name: ci

on:
  push:
    branches: ['dev', 'preprod', 'prod']
  pull_request:
    branches: ['dev', 'preprod', 'prod']

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Connect to HEI AWS CodeArtifact
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sh ./init-npm.sh hei-store npm-hei-school 088312068315

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format:check

      - name: Run Eslint
        run: npm run lint

      - name: Run Build
        run: npm run build

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Connect to HEI AWS CodeArtifact
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sh ./init-npm.sh hei-store npm-hei-school 088312068315

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
